-- ============================================================
--  schema.sql - Schema completo del sistema de gestion
--  Usar: CREATE TABLE IF NOT EXISTS (seguro en bases existentes)
--
--  GENERADO POR generar_schema_sql.py A PARTIR DE schema.json.
--  No editarlo a mano: los cambios se pierden en la proxima corrida.
--  Para agregar o cambiar una tabla, tocar schema.json y volver a
--  correr el generador.
--
--  Generado: 2026-09-30   (47 tablas + _schema_version)
--  Subir a: github.com/surisistemas/migraciones/schema.sql
-- ============================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

-- Control de versiones
CREATE TABLE IF NOT EXISTS `_schema_version` (
  `version`      INT          NOT NULL,
  `descripcion`  VARCHAR(200) NOT NULL DEFAULT '',
  `aplicado_en`  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- acl
CREATE TABLE IF NOT EXISTS `acl` (
  `codigo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nombre` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fantasia` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `direc` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_postal` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `locali` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fax` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `telefono` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cuit` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pos` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tipo_pos` decimal(2,0) DEFAULT NULL,
  `tipo_doc` decimal(2,0) DEFAULT NULL,
  `obs` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provi` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cli_pro` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_estado` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_zona` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_vend` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `clasif` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cl_lista` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `monecc` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `saldo_cc` decimal(12,2) DEFAULT NULL,
  `bloqueo_cc` tinyint(1) DEFAULT NULL,
  `apli_licre` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `limite_cre` decimal(12,2) DEFAULT NULL,
  `impri_eti` tinyint(1) DEFAULT NULL,
  `impri_pa` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bonif_1` decimal(5,2) DEFAULT NULL,
  `bonif_12` decimal(5,2) DEFAULT NULL,
  `bonif_13` decimal(5,2) DEFAULT NULL,
  `bonif_2` decimal(5,2) DEFAULT NULL,
  `desc_art` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `t_pago` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `f_pago1` decimal(3,0) DEFAULT NULL,
  `f_pago2` decimal(3,0) DEFAULT NULL,
  `f_pago3` decimal(3,0) DEFAULT NULL,
  `f_pago4` decimal(3,0) DEFAULT NULL,
  `f_pago5` decimal(3,0) DEFAULT NULL,
  `f_pago6` decimal(3,0) DEFAULT NULL,
  `cod_trans` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ulti_ope` date DEFAULT NULL,
  `liberado` decimal(6,2) DEFAULT NULL,
  `iva_exen` tinyint(1) DEFAULT NULL,
  `ib_tipo` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ib_nro` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `iva_porc` decimal(5,2) DEFAULT NULL,
  `ib_exen` tinyint(1) DEFAULT NULL,
  `ib_porc` decimal(5,2) DEFAULT NULL,
  `ib_exen_901` tinyint(1) DEFAULT NULL,
  `ib_porc_901` decimal(5,2) DEFAULT NULL,
  `IB_EXEN_924` BIT(1) DEFAULT NULL,
  `IB_PORC_924` DECIMAL(16,4) DEFAULT NULL,
  `ib_exen_914` tinyint(1) DEFAULT NULL,
  `ib_porc_914` decimal(5,2) DEFAULT NULL,
  `ib_exen_93` tinyint(1) DEFAULT NULL,
  `ib_porc_93` decimal(5,2) DEFAULT NULL,
  `cl_obs` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cl_anotador` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `impri_opcion` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p_venta` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `f_alta` date DEFAULT NULL,
  `tcompras` decimal(15,2) DEFAULT NULL,
  `modali` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `situa` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mkfecha` date DEFAULT NULL,
  `mkfechaul` date DEFAULT NULL,
  `lote` decimal(5,0) DEFAULT NULL,
  `bonif_22` decimal(5,2) DEFAULT NULL,
  `bonif_23` decimal(5,2) DEFAULT NULL,
  `bonif_3` decimal(5,2) DEFAULT NULL,
  `fcredito` tinyint(1) DEFAULT NULL,
  `fchange` date DEFAULT NULL,
  `id_acl` CHAR(4) DEFAULT NULL,
  `cod_vend2` CHAR(4) DEFAULT NULL,
  `ib_porc_94` decimal(6,2) DEFAULT NULL,
  `ib_exen_94` tinyint(1) DEFAULT NULL,
  `C_MIN` DECIMAL(16,4) DEFAULT NULL,
  `w_user` CHAR(50) DEFAULT NULL,
  `ib_exen_921` tinyint(1) NOT NULL DEFAULT '0',
  `ib_porc_921` DECIMAL(5,2) NOT NULL DEFAULT '0',
  `ib_exen_917` tinyint(1) NOT NULL DEFAULT '0',
  `ib_porc_917` DECIMAL(5,2) NOT NULL DEFAULT '0',
  `wasap` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- acl2
CREATE TABLE IF NOT EXISTS `acl2` (
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `codigo` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `campo` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contenido` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `delete_at` datetime DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_origen` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_sync_version` int NOT NULL DEFAULT '1',
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- af
CREATE TABLE IF NOT EXISTS `af` (
  `ffact` date DEFAULT NULL,
  `comprob` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tipo` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codfact` decimal(3,0) DEFAULT NULL,
  `fnfact` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nombre` VARCHAR(150),
  `ftt` decimal(12,2) DEFAULT NULL,
  `codigo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `direc` VARCHAR(100),
  `locali` VARCHAR(100),
  `cuit` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pos` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tipo_pos` decimal(2,0) DEFAULT NULL,
  `tipo_doc` decimal(2,0) DEFAULT NULL,
  `fst` decimal(12,2) DEFAULT NULL,
  `descu` decimal(10,2) DEFAULT NULL,
  `descu2` decimal(10,2) DEFAULT NULL,
  `reca` decimal(10,2) DEFAULT NULL,
  `n_gra` decimal(12,2) DEFAULT NULL,
  `n_no_gra` decimal(12,2) DEFAULT NULL,
  `impu` decimal(10,2) DEFAULT NULL,
  `iva` decimal(10,2) DEFAULT NULL,
  `iva_105` decimal(10,2) DEFAULT NULL,
  `percep` decimal(10,2) DEFAULT NULL,
  `reib` decimal(10,2) DEFAULT NULL,
  `reib_901` decimal(10,2) DEFAULT NULL,
  `reib_921` decimal(10,2) DEFAULT NULL,
  `reib_917` decimal(10,2) DEFAULT NULL,
  `reib_914` decimal(10,2) DEFAULT NULL,
  `p_descu` decimal(5,2) DEFAULT NULL,
  `p_descu2` decimal(5,2) DEFAULT NULL,
  `p_descu3` decimal(5,2) DEFAULT NULL,
  `p_descu4` decimal(5,2) DEFAULT NULL,
  `p_reca` decimal(5,2) DEFAULT NULL,
  `p_impu` decimal(5,2) DEFAULT NULL,
  `p_percep` decimal(5,2) DEFAULT NULL,
  `p_reib` decimal(5,2) DEFAULT NULL,
  `p_reib_901` decimal(5,2) DEFAULT NULL,
  `p_reib_921` decimal(5,2) DEFAULT NULL,
  `p_reib_917` decimal(5,2) DEFAULT NULL,
  `p_reib_914` decimal(5,2) DEFAULT NULL,
  `cod_zona` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_vend` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `comi_v` decimal(9,2) DEFAULT NULL,
  `moneda` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dolar` DECIMAL(10,4),
  `remii` VARCHAR(200),
  `oc_prov` VARCHAR(200),
  `oc_2` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provi` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `libera` decimal(6,2) DEFAULT NULL,
  `cod_fp` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `plazo` VARCHAR(20),
  `relote` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `transporte` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `impri_opcion` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `precrd` decimal(1,0) DEFAULT NULL,
  `pass` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cae` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vtocae` date DEFAULT NULL,
  `fe` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reib_924` decimal(12,2) DEFAULT NULL,
  `p_reib_924` decimal(6,2) DEFAULT NULL,
  `fecha` datetime(3) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `_pdf_estado` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0=pendiente 1=subido 2=error 3=no_existe',
  `_pdf_subido_en` datetime(3) DEFAULT NULL,
  `_pdf_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_pdf_intentos` tinyint(1) NOT NULL DEFAULT '0',
  `cae_estado` tinyint(1) NOT NULL DEFAULT '1' COMMENT '0=pendiente 1=autorizada 2=rechazada',
  `cae_motivo` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cae_intentos` tinyint(1) NOT NULL DEFAULT '0',
  KEY `idx_cae_estado` (`cae_estado`),
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- af_cobros
CREATE TABLE IF NOT EXISTS `af_cobros` (
  `fnfact` varchar(13) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nro` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codfact` decimal(3,0) DEFAULT NULL,
  `ptovta` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fecha` date DEFAULT NULL,
  `tipo` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `importe` decimal(12,2) DEFAULT NULL,
  `importe_orig` decimal(12,2) DEFAULT NULL,
  `moneda` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dolar` decimal(10,4) DEFAULT NULL,
  `datos` json DEFAULT NULL,
  `pass` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codigo` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_af_cobros_fnfact` (`fnfact`),
  KEY `idx_af_cobros_codigo` (`codigo`),
  KEY `idx_af_cobros_fecha` (`fecha`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- af_obs
CREATE TABLE IF NOT EXISTS `af_obs` (
  `arch` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fnfact` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ffact` date DEFAULT NULL,
  `nro_obs` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `obs` VARCHAR(150),
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- af_obs_local
CREATE TABLE IF NOT EXISTS `af_obs_local` (
  `arch` char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fnfact` varchar(19) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ffact` date DEFAULT NULL,
  `nro_obs` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `obs` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `migrado` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- afd
CREATE TABLE IF NOT EXISTS `afd` (
  `fcant` DECIMAL(13,3) DEFAULT NULL,
  `fcod` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fdesc` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unidad` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fprec` DECIMAL(15,4),
  `bonif` decimal(4,2) DEFAULT NULL,
  `ftotal` decimal(12,2) DEFAULT NULL,
  `cod_orig` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tipo` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fnfact` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `comprob` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codfact` decimal(3,0) DEFAULT NULL,
  `ftotal_siv` decimal(12,3) DEFAULT NULL,
  `f_pu` DECIMAL(15,4),
  `f_lista` DECIMAL(15,4),
  `tribu_iva` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `moneda` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_zona` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_vend` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ffact` date DEFAULT NULL,
  `texva` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `texva2` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codigo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pais` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provi` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tasa_ib` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dolar` DECIMAL(10,4),
  `relote` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nro_despacho` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `r_codfact` decimal(3,0) DEFAULT NULL,
  `r_ptovta` decimal(5,0) DEFAULT NULL,
  `r_nrocpte` decimal(8,0) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- auditoria
CREATE TABLE IF NOT EXISTS `auditoria` (
  `id` int NOT NULL AUTO_INCREMENT,
  `fecha` datetime DEFAULT NULL,
  `comando` char(10) DEFAULT NULL,
  `data` text,
  `tabla` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- bancos
CREATE TABLE IF NOT EXISTS `bancos` (
  `cod_bco` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fvto` date DEFAULT NULL,
  `nro` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ing_egr` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `importe` decimal(12,2) DEFAULT NULL,
  `saldo` decimal(12,2) DEFAULT NULL,
  `fecha` date DEFAULT NULL,
  `comprob` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `detalle` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fechai` date DEFAULT NULL,
  `form_tipo` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `form_nro` VARCHAR(15),
  `pass` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `obs` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `confirmado` tinyint(1) DEFAULT NULL,
  `e_cheque` tinyint(1) DEFAULT NULL,
  `codfact` decimal(3,0) DEFAULT NULL,
  `ptovta` decimal(5,0) DEFAULT NULL,
  `codigo` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- cheques
CREATE TABLE IF NOT EXISTS `cheques` (
  `f_gene` date DEFAULT NULL,
  `fecha` date DEFAULT NULL,
  `importe` decimal(12,2) DEFAULT NULL,
  `estado` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codigo` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `numero` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `orden` decimal(8,0) DEFAULT NULL,
  `receptor` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fechar` date DEFAULT NULL,
  `banco` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `titular` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cuit` varchar(13) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `clearing` decimal(2,0) DEFAULT NULL,
  `alaorden` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pass` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `valor` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `f_tipo_i` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `f_nro_i` varchar(13) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `f_tipo_e` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `f_nro_e` varchar(13) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `relote` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nro_cta` varchar(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cpostal` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_bcoorig` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sucursal` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cmc7` varchar(31) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `e_cheque` tinyint(1) DEFAULT NULL,
  `codfact` decimal(3,0) DEFAULT NULL,
  `ptovta` decimal(5,0) DEFAULT NULL,
  `nro` decimal(8,0) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- comision
CREATE TABLE IF NOT EXISTS `comision` (
  `fcc` date DEFAULT NULL,
  `debe` decimal(10,2) DEFAULT NULL,
  `haber` decimal(10,2) DEFAULT NULL,
  `saldo` decimal(15,2) DEFAULT NULL,
  `saldo_reg` decimal(10,2) DEFAULT NULL,
  `detalle` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dolar` DECIMAL(10,4),
  `codigo` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_vend` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `recibo` varchar(7) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `imporeci` decimal(10,2) DEFAULT NULL,
  `ftt` decimal(10,2) DEFAULT NULL,
  `pass` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- contable
CREATE TABLE IF NOT EXISTS `contable` (
  `fecha` date DEFAULT NULL,
  `c_debe` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `c_haber` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `importe` decimal(15,2) DEFAULT NULL,
  `detalle` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `moneda` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dolar` DECIMAL(10,4),
  `form_tipo` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `form_nro` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `transfe` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `asi` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pass` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sucursal` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ctacte_d
CREATE TABLE IF NOT EXISTS `ctacte_d` (
  `fcc` date DEFAULT NULL,
  `fo` date DEFAULT NULL,
  `codigo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `detalle` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `moneda` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `debe` decimal(12,2) DEFAULT NULL,
  `haber` decimal(12,2) DEFAULT NULL,
  `saldo` decimal(12,2) DEFAULT NULL,
  `DOLAR` DECIMAL(20,4) DEFAULT NULL,
  `saldo_reg` decimal(12,2) DEFAULT NULL,
  `saldori` decimal(12,2) DEFAULT NULL,
  `comi_reg` decimal(10,2) DEFAULT NULL,
  `cod_vend` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pass` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ptoventa` decimal(5,0) DEFAULT NULL,
  `numero` decimal(8,0) DEFAULT NULL,
  `codfact` decimal(3,0) DEFAULT NULL,
  `fecha` datetime(3) DEFAULT NULL,
  `fchange` datetime(3) DEFAULT NULL,
  `identify` int DEFAULT NULL,
  `cod_vend2` CHAR(4) DEFAULT NULL,
  `COMI_REG2` DECIMAL(14,4) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sincro_identify` (`identify`),
  KEY `idx_sincro_codigo` (`codigo`),
  KEY `idx_sincro_fo_deleted` (`fo`, `deleted_at`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ctacte_h
CREATE TABLE IF NOT EXISTS `ctacte_h` (
  `fcc` date DEFAULT NULL,
  `fo` date DEFAULT NULL,
  `codigo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `detalle` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `moneda` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `debe` decimal(15,2) DEFAULT NULL,
  `haber` decimal(15,2) DEFAULT NULL,
  `saldo` decimal(15,2) DEFAULT NULL,
  `DOLAR` DECIMAL(15,4) DEFAULT NULL,
  `saldo_reg` decimal(15,2) DEFAULT NULL,
  `saldori` decimal(12,2) DEFAULT NULL,
  `pass` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codfact` decimal(3,0) DEFAULT NULL,
  `ptoventa` decimal(5,0) DEFAULT NULL,
  `numero` decimal(8,0) DEFAULT NULL,
  `fecha` datetime(3) DEFAULT NULL,
  `fchange` datetime(3) DEFAULT NULL,
  `identify` bigint DEFAULT NULL,
  `saldo_ori` decimal(15,2) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sincro_identify` (`identify`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- da_configuraciones
CREATE TABLE IF NOT EXISTS `da_configuraciones` (
  `clave` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `valor` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `descripcion` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`_id`),
  UNIQUE KEY `idx_clave_unica` (`clave`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- depo_st
CREATE TABLE IF NOT EXISTS `depo_st` (
  `cod` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_depo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cant` decimal(14,2) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_cod` (`cod`,`cod_depo`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- exchange_rates
CREATE TABLE IF NOT EXISTS `exchange_rates` (
  `currency` char(3) NOT NULL,
  `rate_ars` decimal(18,6) NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`currency`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- marca
CREATE TABLE IF NOT EXISTS `marca` (
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `marca` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `path_lista` varchar(250) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lista_nro` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lista_fecha` date DEFAULT NULL,
  `_uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- modelos
CREATE TABLE IF NOT EXISTS `modelos` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `codigo` char(10) NOT NULL,
  `nombre` varchar(100) NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  KEY `nombre` (`nombre`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- modelos_codigos
CREATE TABLE IF NOT EXISTS `modelos_codigos` (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_stock` varchar(25) NOT NULL,
  `id_modelo` char(10) NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- monedas
CREATE TABLE IF NOT EXISTS `monedas` (
  `moneda` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `descripcion` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cotizacion` decimal(12,2) NOT NULL DEFAULT '1.00',
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`_id`),
  UNIQUE KEY `idx_moneda_unica` (`moneda`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- mov_caja
CREATE TABLE IF NOT EXISTS `mov_caja` (
  `nro_caja` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fecha_caja` datetime(3) DEFAULT NULL,
  `fecha` date DEFAULT NULL,
  `detalle` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `moneda` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ing_egr` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `importe` decimal(12,2) DEFAULT NULL,
  `saldo` decimal(12,2) DEFAULT NULL,
  `form_tipo` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `form_nro` VARCHAR(15),
  `dolar` DECIMAL(10,4),
  `pass` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `relote` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codfact` decimal(3,0) DEFAULT NULL,
  `ptovta` decimal(5,0) DEFAULT NULL,
  `nro` decimal(8,0) DEFAULT NULL,
  `codigo` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- mstock
CREATE TABLE IF NOT EXISTS `mstock` (
  `fecha` date DEFAULT NULL,
  `cod` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `e_s` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `motivo` VARCHAR(20),
  `mov_cant` decimal(12,2) DEFAULT NULL,
  `detalle` VARCHAR(100),
  `pass` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_depo` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codigo` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `obs` VARCHAR(150),
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ncompro
CREATE TABLE IF NOT EXISTS `ncompro` (
  `nro` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `f_a` tinyint(1) DEFAULT NULL,
  `nc_a` tinyint(1) DEFAULT NULL,
  `nd_a` tinyint(1) DEFAULT NULL,
  `f_e` tinyint(1) DEFAULT NULL,
  `f_b` tinyint(1) DEFAULT NULL,
  `nc_b` tinyint(1) DEFAULT NULL,
  `nd_b` tinyint(1) DEFAULT NULL,
  `t_b` tinyint(1) DEFAULT NULL,
  `r_x` tinyint(1) DEFAULT NULL,
  `f_c` tinyint(1) DEFAULT NULL,
  `r_f` tinyint(1) DEFAULT NULL,
  `r_fb` tinyint(1) DEFAULT NULL,
  `pr` tinyint(1) DEFAULT NULL,
  `oc` tinyint(1) DEFAULT NULL,
  `op` tinyint(1) DEFAULT NULL,
  `np` tinyint(1) DEFAULT NULL,
  `reci` tinyint(1) DEFAULT NULL,
  `pc` tinyint(1) DEFAULT NULL,
  `prof` tinyint(1) DEFAULT NULL,
  `confirma` tinyint(1) DEFAULT NULL,
  `retib` tinyint(1) DEFAULT NULL,
  `sucursal` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cotizpro` tinyint(1) DEFAULT NULL,
  `ing_f` tinyint(1) DEFAULT NULL,
  `egr_f` tinyint(1) DEFAULT NULL,
  `cantlinea` decimal(3,0) DEFAULT NULL,
  `reporte` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reporte2` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `impresora` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `elij_imp` tinyint(1) DEFAULT NULL,
  `copias` decimal(2,0) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- numem
CREATE TABLE IF NOT EXISTS `numem` (
  `cod_bco` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `banco` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lastchk` decimal(12,0) DEFAULT NULL,
  `lastchke` decimal(12,0) DEFAULT NULL,
  `codigo` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cuit` varchar(13) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codtarjepro` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tarjepro` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tarjeimpu` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nro_cuenta` varchar(22) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cbu` varchar(22) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `moneda` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `saldo_act` decimal(15,2) DEFAULT NULL,
  `activo` tinyint(1) DEFAULT '1',
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- obras
CREATE TABLE IF NOT EXISTS `obras` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `nombre` varchar(50) NOT NULL,
  `contacto` varchar(50) NOT NULL,
  `autorizado` varchar(50) NOT NULL,
  `domicilio` varchar(50) NOT NULL,
  `telefono` varchar(50) NOT NULL,
  `codigo` char(4) NOT NULL,
  `codigofac` char(4) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- obras_facturas
CREATE TABLE IF NOT EXISTS `obras_facturas` (
  `fnfact` char(15) NOT NULL,
  `id_obra` int NOT NULL,
  `codfact` int NOT NULL,
  `pventa` int NOT NULL,
  `numero` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ped
CREATE TABLE IF NOT EXISTS `ped` (
  `item` decimal(4,0) DEFAULT NULL,
  `ffact` date DEFAULT NULL,
  `hora` datetime(3) DEFAULT NULL,
  `fvence` date DEFAULT NULL,
  `fnfact` decimal(6,0) DEFAULT NULL,
  `nombre` VARCHAR(150),
  `ftt` decimal(12,2) DEFAULT NULL,
  `pendiente` tinyint(1) DEFAULT NULL,
  `aprobado` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fec_apro` datetime(3) DEFAULT NULL,
  `preparado` tinyint(1) DEFAULT NULL,
  `f_preparado` datetime(3) DEFAULT NULL,
  `cod_estado` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_preparador` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p_despacho` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codigo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cuit` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pos` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fst` decimal(12,2) DEFAULT NULL,
  `descu` decimal(10,2) DEFAULT NULL,
  `descu2` decimal(10,2) DEFAULT NULL,
  `reca` decimal(10,2) DEFAULT NULL,
  `n_gra` decimal(12,2) DEFAULT NULL,
  `n_no_gra` decimal(12,2) DEFAULT NULL,
  `impu` decimal(10,2) DEFAULT NULL,
  `iva` decimal(10,2) DEFAULT NULL,
  `iva_105` decimal(10,2) DEFAULT NULL,
  `p_descu` decimal(5,2) DEFAULT NULL,
  `p_descu2` decimal(5,2) DEFAULT NULL,
  `p_descu3` decimal(5,2) DEFAULT NULL,
  `p_descu4` decimal(5,2) DEFAULT NULL,
  `p_reca` decimal(5,2) DEFAULT NULL,
  `p_impu` decimal(5,2) DEFAULT NULL,
  `cod_vend` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `moneda` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dolar` DECIMAL(10,4),
  `provi` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `libera` decimal(6,2) DEFAULT NULL,
  `cod_fp` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `plazo` VARCHAR(20),
  `fentre` date DEFAULT NULL,
  `hentre` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pesot` decimal(8,3) DEFAULT NULL,
  `lote` decimal(5,0) DEFAULT NULL,
  `np_oc` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `np_oc_2` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lista` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `precrd` decimal(1,0) DEFAULT NULL,
  `pass_apro` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pass` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p_reib` decimal(5,2) DEFAULT NULL,
  `p_reib_901` decimal(5,2) DEFAULT NULL,
  `p_reib_921` decimal(5,2) DEFAULT NULL,
  `p_reib_917` decimal(5,2) DEFAULT NULL,
  `p_reib_914` decimal(5,2) DEFAULT NULL,
  `reib` decimal(10,2) DEFAULT NULL,
  `reib_901` decimal(10,2) DEFAULT NULL,
  `reib_921` decimal(10,2) DEFAULT NULL,
  `reib_914` decimal(10,2) DEFAULT NULL,
  `reib_917` decimal(10,2) DEFAULT NULL,
  `fchange` datetime(3) DEFAULT NULL,
  `tipo_pos` decimal(2,0) DEFAULT NULL,
  `tipo_doc` decimal(2,0) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ped_d
CREATE TABLE IF NOT EXISTS `ped_d` (
  `fcant` decimal(9,3) DEFAULT NULL,
  `menos` decimal(9,3) DEFAULT NULL,
  `pendi` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dentrega` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `item` decimal(4,0) DEFAULT NULL,
  `cnt_preparada` decimal(6,0) DEFAULT NULL,
  `preparado` tinyint(1) DEFAULT NULL,
  `f_preparado` datetime(3) DEFAULT NULL,
  `cod_preparada` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_preparo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_estado` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fcod` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fdesc` VARCHAR(255),
  `unidad` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `f_pu` decimal(15,2) DEFAULT NULL,
  `fprec` DECIMAL(15,4),
  `bonif` decimal(4,2) DEFAULT NULL,
  `ftotal` decimal(12,2) DEFAULT NULL,
  `cod_orig` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tribu_iva` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codigo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ffact` date DEFAULT NULL,
  `cod_vend` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `texva` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `texva2` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fnfact` decimal(6,0) DEFAULT NULL,
  `lote` decimal(5,0) DEFAULT NULL,
  `nro_despacho` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fchange` datetime(3) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ped_d_local
CREATE TABLE IF NOT EXISTS `ped_d_local` (
  `id` int NOT NULL AUTO_INCREMENT,
  `fcant` decimal(6,0) DEFAULT NULL,
  `menos` decimal(6,0) DEFAULT NULL,
  `pendi` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dentrega` char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `item` decimal(4,0) DEFAULT NULL,
  `cnt_preparada` decimal(6,0) DEFAULT NULL,
  `preparado` bit(1) DEFAULT NULL,
  `f_preparado` datetime DEFAULT NULL,
  `cod_preparada` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_preparo` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_estado` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fcod` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fdesc` varchar(65) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unidad` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `f_pu` decimal(12,2) DEFAULT NULL,
  `fprec` decimal(12,2) DEFAULT NULL,
  `bonif` decimal(4,2) DEFAULT NULL,
  `ftotal` decimal(12,2) DEFAULT NULL,
  `cod_orig` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tribu_iva` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codigo` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ffact` date DEFAULT NULL,
  `cod_vend` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `texva` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `texva2` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fnfact` int DEFAULT NULL,
  `lote` decimal(5,0) DEFAULT NULL,
  `nro_despacho` varchar(21) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `migrado` int DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `id_web` int DEFAULT NULL,
  `id_ped_local` int DEFAULT NULL,
  `id_empresa` int DEFAULT NULL,
  `id_sucursal` int DEFAULT NULL,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'API',
  PRIMARY KEY (`id`),
  KEY `idx_fcod` (`fcod`),
  KEY `idx_pdl_ped` (`id_ped_local`),
  KEY `idx_pdl_web` (`id_web`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ped_local
CREATE TABLE IF NOT EXISTS `ped_local` (
  `id` int NOT NULL AUTO_INCREMENT,
  `item` int DEFAULT NULL,
  `ffact` datetime DEFAULT NULL,
  `hora` datetime DEFAULT NULL,
  `fvence` datetime DEFAULT NULL,
  `fnfact` int NOT NULL DEFAULT '0',
  `nombre` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ftt` decimal(12,2) NOT NULL DEFAULT '0.00',
  `pendiente` int NOT NULL DEFAULT '0',
  `aprobado` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fec_apro` datetime DEFAULT NULL,
  `preparado` int NOT NULL DEFAULT '0',
  `f_preparado` datetime DEFAULT NULL,
  `cod_estado` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_preparado` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p_despacho` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codigo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cuit` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pos` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fst` decimal(12,2) NOT NULL DEFAULT '0.00',
  `descu` decimal(10,2) NOT NULL DEFAULT '0.00',
  `descu2` decimal(10,2) NOT NULL DEFAULT '0.00',
  `reca` decimal(10,2) NOT NULL DEFAULT '0.00',
  `n_gra` decimal(12,2) NOT NULL DEFAULT '0.00',
  `n_no_gra` decimal(12,2) NOT NULL DEFAULT '0.00',
  `impu` decimal(10,2) NOT NULL DEFAULT '0.00',
  `iva` decimal(10,2) NOT NULL DEFAULT '0.00',
  `iva_105` decimal(10,2) NOT NULL DEFAULT '0.00',
  `p_descu` decimal(5,2) NOT NULL DEFAULT '0.00',
  `p_descu2` decimal(5,2) NOT NULL DEFAULT '0.00',
  `p_descu3` decimal(5,2) NOT NULL DEFAULT '0.00',
  `p_descu4` decimal(5,2) NOT NULL DEFAULT '0.00',
  `p_reca` decimal(5,2) NOT NULL DEFAULT '0.00',
  `p_impu` decimal(5,2) NOT NULL DEFAULT '0.00',
  `cod_vend` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `moneda` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dolar` DECIMAL(10,4),
  `provi` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `libera` decimal(6,2) DEFAULT '0.00',
  `cod_fp` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `plazo` VARCHAR(20),
  `fentre` datetime DEFAULT NULL,
  `hentre` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pesot` decimal(8,3) DEFAULT '0.000',
  `lote` int DEFAULT NULL,
  `np_oc` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `np_oc_2` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lista` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `precrd` int DEFAULT NULL,
  `pass_apro` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pass` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p_reib` decimal(5,2) DEFAULT '0.00',
  `p_reib_901` decimal(5,2) DEFAULT '0.00',
  `p_reib_921` decimal(5,2) DEFAULT '0.00',
  `p_reib_917` decimal(5,2) DEFAULT '0.00',
  `p_reib_914` decimal(5,2) DEFAULT '0.00',
  `reib` decimal(10,2) DEFAULT '0.00',
  `reib_901` decimal(10,2) DEFAULT '0.00',
  `reib_921` decimal(10,2) DEFAULT '0.00',
  `reib_917` decimal(10,2) DEFAULT '0.00',
  `reib_914` decimal(10,2) DEFAULT '0.00',
  `tipo_pos` int DEFAULT NULL,
  `tipo_doc` int DEFAULT NULL,
  `migrado` int DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `id_web` int DEFAULT NULL,
  `nro_pedido_erp` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `estado_local` tinyint(1) NOT NULL DEFAULT '0',
  `fecha_proceso` datetime DEFAULT NULL,
  `obs_local` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `id_empresa` int DEFAULT NULL,
  `id_sucursal` int DEFAULT NULL,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '1',
  `fact_nro` varchar(20) DEFAULT NULL,
  `fact_tipo` varchar(3) DEFAULT NULL,
  `fact_letra` varchar(1) DEFAULT NULL,
  `fact_fecha` datetime DEFAULT NULL,
  `fact_cae` varchar(20) DEFAULT NULL,
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'API',
  PRIMARY KEY (`id`),
  KEY `idx_estado_local` (`estado_local`),
  KEY `idx_sync_estado` (`_sync_estado`),
  KEY `idx_codigo_cli` (`codigo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ped_web_meta
CREATE TABLE IF NOT EXISTS `ped_web_meta` (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_ped` int NOT NULL,
  `order_id` varchar(50) DEFAULT NULL,
  `comprador_nickname` varchar(100) DEFAULT NULL,
  `comprador_telefono` varchar(50) DEFAULT NULL,
  `envio_calle` varchar(255) DEFAULT NULL,
  `envio_cp` varchar(20) DEFAULT NULL,
  `envio_localidad` varchar(100) DEFAULT NULL,
  `envio_provincia` varchar(100) DEFAULT NULL,
  `carrier_nombre` varchar(100) DEFAULT NULL,
  `tracking_id` varchar(100) DEFAULT NULL,
  `meta_key` varchar(50) DEFAULT NULL,
  `meta_value` text DEFAULT NULL,
  `raw_payload` json DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '1',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_ped` (`id_ped`),
  KEY `idx_order` (`order_id`),
  KEY `idx_key` (`meta_key`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ped_web_pagos
CREATE TABLE IF NOT EXISTS `ped_web_pagos` (
  `id` int NOT NULL AUTO_INCREMENT,
  `id_ped` int NOT NULL,
  `ml_order_id` varchar(50) DEFAULT NULL,
  `pack_id` varchar(50) DEFAULT NULL,
  `payment_id` varchar(50) DEFAULT NULL,
  `origen` varchar(20) DEFAULT 'ML',
  `forma_pago_cod` varchar(10) DEFAULT 'ML',
  `metodo_pago` varchar(50) DEFAULT NULL,
  `tarjeta_banco` varchar(50) DEFAULT NULL,
  `cuotas` int DEFAULT '1',
  `monto_bruto` DECIMAL(12,2) NULL DEFAULT 0.00,
  `comision_pasarela` decimal(10,2) DEFAULT '0.00',
  `impuestos_pasarela` decimal(10,2) DEFAULT '0.00',
  `costo_envio` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `monto_neto` DECIMAL(12,2) NULL DEFAULT 0.00,
  `monto_devuelto` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `estado_pago` varchar(20) DEFAULT 'approved',
  `estado_detalle` varchar(50) DEFAULT NULL,
  `fecha_cobro` datetime DEFAULT NULL,
  `date_approved` datetime DEFAULT NULL,
  `money_release_date` datetime DEFAULT NULL,
  `conciliado` tinyint NOT NULL DEFAULT '0',
  `fnfact` varchar(20) DEFAULT NULL,
  `cod_bco` varchar(2) DEFAULT NULL,
  `fec_concil` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '1',
  `_eliminado`   tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_ped` (`id_ped`),
  KEY `idx_payment` (`payment_id`),
  KEY `idx_ml_order` (`ml_order_id`),
  KEY `idx_pwp_conciliado` (`id_ped`,`conciliado`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- perc_ret
CREATE TABLE IF NOT EXISTS `perc_ret` (
  `fecha` date DEFAULT NULL,
  `importe` decimal(10,2) DEFAULT NULL,
  `estado` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ncomprob` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codigo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fechaliq` date DEFAULT NULL,
  `valor` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provi` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `f_tipo_i` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `f_nro_i` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `f_tipo_e` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `f_nro_e` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cuit` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `alicuota` decimal(5,2) DEFAULT NULL,
  `codfact` decimal(3,0) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_ncomprob` (`ncomprob`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- pre
CREATE TABLE IF NOT EXISTS `pre` (
  `ffact` date DEFAULT NULL,
  `hora` datetime(3) DEFAULT NULL,
  `fvence` date DEFAULT NULL,
  `aprobado` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `autorizado` tinyint(1) DEFAULT NULL,
  `user_autori` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fnfact` decimal(6,0) DEFAULT NULL,
  `nombre` VARCHAR(150),
  `ftt` decimal(12,2) DEFAULT NULL,
  `codigo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cuit` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pos` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fst` decimal(12,2) DEFAULT NULL,
  `descu` decimal(10,2) DEFAULT NULL,
  `descu2` decimal(10,2) DEFAULT NULL,
  `reca` decimal(10,2) DEFAULT NULL,
  `n_gra` decimal(12,2) DEFAULT NULL,
  `n_no_gra` decimal(12,2) DEFAULT NULL,
  `impu` decimal(10,2) DEFAULT NULL,
  `iva` decimal(10,2) DEFAULT NULL,
  `iva_105` decimal(10,2) DEFAULT NULL,
  `p_descu` decimal(5,2) DEFAULT NULL,
  `p_descu2` decimal(5,2) DEFAULT NULL,
  `p_descu3` decimal(5,2) DEFAULT NULL,
  `p_descu4` decimal(5,2) DEFAULT NULL,
  `p_reca` decimal(5,2) DEFAULT NULL,
  `p_impu` decimal(5,2) DEFAULT NULL,
  `cod_vend` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `moneda` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dolar` DECIMAL(10,4),
  `provi` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `libera` decimal(6,2) DEFAULT NULL,
  `cod_fp` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `plazo` VARCHAR(20),
  `lote` decimal(5,0) DEFAULT NULL,
  `lista` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `precrd` decimal(1,0) DEFAULT NULL,
  `pass` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p_reib` decimal(5,2) DEFAULT NULL,
  `p_reib_921` decimal(5,2) DEFAULT NULL,
  `p_reib_901` decimal(5,2) DEFAULT NULL,
  `p_reib_914` decimal(10,2) DEFAULT NULL,
  `p_reib_917` decimal(5,2) DEFAULT NULL,
  `reib` decimal(10,2) DEFAULT NULL,
  `reib_901` decimal(10,2) DEFAULT NULL,
  `reib_921` decimal(10,2) DEFAULT NULL,
  `reib_917` decimal(10,2) DEFAULT NULL,
  `reib_914` decimal(10,2) DEFAULT NULL,
  `fchange` datetime(3) DEFAULT NULL,
  `tipo_pos` decimal(2,0) DEFAULT NULL,
  `tipo_doc` decimal(2,0) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- pre_d
CREATE TABLE IF NOT EXISTS `pre_d` (
  `fcant` decimal(9,3) DEFAULT NULL,
  `dentrega` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `item` decimal(4,0) DEFAULT NULL,
  `fcod` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fdesc` VARCHAR(255),
  `unidad` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `f_pu` decimal(15,2) DEFAULT NULL,
  `fprec` DECIMAL(15,4),
  `bonif` decimal(4,2) DEFAULT NULL,
  `ftotal` decimal(12,2) DEFAULT NULL,
  `cod_orig` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fnfact` decimal(6,0) DEFAULT NULL,
  `tribu_iva` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ffact` date DEFAULT NULL,
  `texva` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `texva2` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lote` decimal(5,0) DEFAULT NULL,
  `nro_despacho` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fchange` datetime(3) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- recibo_aplica
CREATE TABLE IF NOT EXISTS `recibo_aplica` (
  `id`               bigint        NOT NULL AUTO_INCREMENT,
  `id_recibo` bigint DEFAULT NULL,
  `nro_recibo`       varchar(13)   NOT NULL,
  `codigo_cliente`   varchar(4)    NOT NULL,
  `fnfact` VARCHAR(30),
  `codfact`          decimal(3,0)  DEFAULT NULL,
  `fecha_fact`       date          DEFAULT NULL,
  `detalle`          varchar(80)   DEFAULT NULL,
  `moneda`           varchar(3)    DEFAULT '$',
  `debe`             decimal(15,2) DEFAULT '0.00',
  `haber`            decimal(15,2) DEFAULT '0.00',
  `saldo_anterior`   decimal(15,2) NOT NULL DEFAULT '0.00',
  `importe_aplicado` decimal(15,2) NOT NULL DEFAULT '0.00',
  `saldo_nuevo`      decimal(15,2) NOT NULL DEFAULT '0.00',
  `comi_reg`         decimal(12,2) DEFAULT '0.00',
  `dolar`            decimal(10,4) DEFAULT NULL,
  `cod_vend`         varchar(4)    DEFAULT NULL,
  `_uuid`            char(36)      NOT NULL DEFAULT (uuid()),
  `_creado_en`       datetime(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en`   datetime(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_origen`          varchar(20)   NOT NULL DEFAULT 'ERP',
  `update_at`        datetime      DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_recibo`  (`id_recibo`),
  KEY `idx_fnfact`  (`fnfact`),
  KEY `idx_cliente` (`codigo_cliente`),
  KEY `idx_nro`     (`nro_recibo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- recibo_cab
CREATE TABLE IF NOT EXISTS `recibo_cab` (
  `id`              bigint          NOT NULL AUTO_INCREMENT,
  `nro_recibo`      varchar(13)     NOT NULL COMMENT 'Ej: 0011-00000123',
  `fecha`           date            NOT NULL,
  `codigo_cliente`  varchar(4)      NOT NULL,
  `nombre`          varchar(100)     NOT NULL,
  `cuit`            varchar(13)     DEFAULT NULL,
  `saldo_anterior`  decimal(15,2)   NOT NULL DEFAULT '0.00',
  `importe_total`   decimal(15,2)   NOT NULL DEFAULT '0.00',
  `moneda`          varchar(3)      NOT NULL DEFAULT '$',
  `dolar`           decimal(10,4)   DEFAULT NULL,
  `pass`            varchar(4)      DEFAULT NULL,
  `sucursal`        varchar(4)      DEFAULT NULL,
  `tipo` VARCHAR(5),
  `cod_vend`        varchar(4)      DEFAULT NULL,
  `ncompro`         varchar(13)     DEFAULT NULL,
  `observaciones`   varchar(200)    DEFAULT NULL,
  `anulado`         tinyint(1)      NOT NULL DEFAULT '0',
  `fecha_anulacion` date            DEFAULT NULL,
  `pass_anulacion`  varchar(4)      DEFAULT NULL,
  `_uuid`           char(36)        NOT NULL DEFAULT (uuid()),
  `_creado_en`      datetime(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en`  datetime(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_origen`         varchar(20)     NOT NULL DEFAULT 'ERP',
  `_eliminado`      tinyint(1)      NOT NULL DEFAULT '0',
  `update_at`       datetime        DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_nro_recibo` (`nro_recibo`),
  KEY `idx_cliente` (`codigo_cliente`),
  KEY `idx_fecha` (`fecha`),
  KEY `idx_tipo` (`tipo`),
  KEY `idx_anulado` (`anulado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- recibo_cobro
CREATE TABLE IF NOT EXISTS `recibo_cobro` (
  `id`          bigint        NOT NULL AUTO_INCREMENT,
  `id_recibo` bigint DEFAULT NULL,
  `nro_recibo`  varchar(13)   NOT NULL,
  `tipo_cobro`  varchar(15)   NOT NULL,
  `importe`     decimal(15,2) NOT NULL DEFAULT '0.00',
  `moneda`      varchar(3)    NOT NULL DEFAULT '$',
  `dolar`       decimal(10,4) DEFAULT NULL,
  `tarje`       varchar(4)    DEFAULT NULL,
  `nro_tarje`   varchar(25)   DEFAULT NULL,
  `cupon`       varchar(15)   DEFAULT NULL,
  `autoriz`     varchar(15)   DEFAULT NULL,
  `cod_bco`     varchar(2)    DEFAULT NULL,
  `nro_doc`     varchar(20)   DEFAULT NULL,
  `titular`     varchar(40)   DEFAULT NULL,
  `cuit_doc`    varchar(13)   DEFAULT NULL,
  `fecha_vto`   date          DEFAULT NULL,
  `clearing`    varchar(1)    DEFAULT NULL,
  `cod_ret`     varchar(6)    DEFAULT NULL,
  `nro_ret`     varchar(15)   DEFAULT NULL,
  `datos`       json          DEFAULT NULL,
  `_uuid`       char(36)      NOT NULL DEFAULT (uuid()),
  `_creado_en`  datetime(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_origen`     varchar(20)   NOT NULL DEFAULT 'ERP',
  `update_at`   datetime      DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_recibo`     (`id_recibo`),
  KEY `idx_nro`        (`nro_recibo`),
  KEY `idx_tipo_cobro` (`tipo_cobro`),
  KEY `idx_cod_bco`    (`cod_bco`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- relacion_comprobantes
CREATE TABLE IF NOT EXISTS `relacion_comprobantes` (
  `id` int NOT NULL AUTO_INCREMENT,
  `codfact` int DEFAULT NULL,
  `ptovta` int DEFAULT NULL,
  `nro_cpte` bigint DEFAULT NULL,
  `tipo_doc` varchar(4) DEFAULT NULL,
  `ptovta_relacion` int DEFAULT NULL,
  `cpte_relacion` varchar(20) DEFAULT NULL,
  `fecha` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- rem
CREATE TABLE IF NOT EXISTS `rem` (
  `fnfact` varchar(13) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ffact` date DEFAULT NULL,
  `codigo` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nombre` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `direc` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `locali` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provi` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tipo` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pass` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `comprob` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `moneda` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dolar` DECIMAL(10,4),
  `plazo` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `obs` VARCHAR(150),
  `cuit` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pos` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_vend` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_zona` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `np_oc` VARCHAR(255),
  `np_oc2` VARCHAR(255),
  `valor` decimal(12,2) DEFAULT NULL,
  `cod_trans` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pendi` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pesot` decimal(8,3) DEFAULT NULL,
  `bultos` decimal(8,0) DEFAULT NULL,
  `precrd` decimal(1,0) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- rem_d
CREATE TABLE IF NOT EXISTS `rem_d` (
  `fnfact` varchar(13) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ffact` date DEFAULT NULL,
  `fcod` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fdesc` VARCHAR(255),
  `unidad` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fcant` decimal(9,3) DEFAULT NULL,
  `f_pu` decimal(15,4) DEFAULT NULL,
  `fprec` DECIMAL(15,4),
  `bonif` decimal(5,2) DEFAULT NULL,
  `ftotal` decimal(15,4) DEFAULT NULL,
  `moneda` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tipo` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codigo` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_vend` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_zona` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tribu_iva` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_orig` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cbte_pv` decimal(5,0) DEFAULT NULL,
  `cbte_cod` decimal(3,0) DEFAULT NULL,
  `cbte_nro` decimal(8,0) DEFAULT NULL,
  `menos` decimal(6,0) DEFAULT NULL,
  `texva` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `texva2` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pendi` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pais` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nro_despacho` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- stock
CREATE TABLE IF NOT EXISTS `stock` (
  `cod` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mat` varchar(70) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `marca` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `linea` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unidad` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cantxbulto` decimal(6,0) DEFAULT NULL,
  `com_minima` decimal(6,0) DEFAULT NULL,
  `moneda` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `plp0` decimal(12,2) DEFAULT NULL,
  `plp` DECIMAL(15,4),
  `PU` DECIMAL(16,4) DEFAULT NULL,
  `lista1` DECIMAL(15,4),
  `lista2` DECIMAL(15,4),
  `lista3` DECIMAL(15,4),
  `lista4` DECIMAL(15,4),
  `lista5` DECIMAL(15,4),
  `lista6` DECIMAL(15,4),
  `lista7` DECIMAL(15,4),
  `lista8` DECIMAL(15,4),
  `s_prec` date DEFAULT NULL,
  `sm` decimal(6,0) DEFAULT NULL,
  `rubro` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `subrubro` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_orig` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pais` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `visible` tinyint(1) DEFAULT NULL,
  `bloqueado` tinyint(1) DEFAULT NULL,
  `imprime` tinyint(1) DEFAULT NULL,
  `cod_orig2` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_orig3` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `impu_c` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `impu_v` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `veriexis` tinyint(1) DEFAULT NULL,
  `comision` decimal(5,2) DEFAULT NULL,
  `falta` date DEFAULT NULL,
  `pass` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pesoxuni` decimal(8,3) DEFAULT NULL,
  `tribu_iva` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tasa_ib` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `st_obs` VARCHAR(150),
  `imp_eti` tinyint(1) DEFAULT NULL,
  `f_venta` date DEFAULT NULL,
  `f_compra` date DEFAULT NULL,
  `f_prec` date DEFAULT NULL,
  `f_precbase` date DEFAULT NULL,
  `st_prov` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `st_prov2` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `st_prov3` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bonif` decimal(5,2) DEFAULT NULL,
  `desc_a` decimal(5,2) DEFAULT NULL,
  `desc_b` decimal(5,2) DEFAULT NULL,
  `desc_c` decimal(5,2) DEFAULT NULL,
  `por_prov` decimal(6,2) DEFAULT NULL,
  `por_prov2` decimal(6,2) DEFAULT NULL,
  `por_prov3` decimal(6,2) DEFAULT NULL,
  `por_prov4` decimal(6,2) DEFAULT NULL,
  `por_lista1` decimal(8,3) DEFAULT NULL,
  `por_lista2` decimal(8,3) DEFAULT NULL,
  `por_lista3` decimal(8,3) DEFAULT NULL,
  `por_lista4` decimal(8,3) DEFAULT NULL,
  `por_lista5` decimal(8,3) DEFAULT NULL,
  `por_lista6` decimal(8,3) DEFAULT NULL,
  `por_lista7` decimal(8,3) DEFAULT NULL,
  `por_lista8` decimal(8,3) DEFAULT NULL,
  `ok_grafico` tinyint(1) DEFAULT NULL,
  `grafico` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tecnico` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `barra` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dun14` varchar(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `st_memo` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `mini_lista` tinyint(1) DEFAULT NULL,
  `cavenmi` decimal(6,0) DEFAULT NULL,
  `cavenmip` decimal(3,2) DEFAULT NULL,
  `oferta` decimal(1,0) DEFAULT NULL,
  `scri` decimal(6,0) DEFAULT NULL,
  `std_montaj` decimal(8,3) DEFAULT NULL,
  `web` tinyint(1) DEFAULT NULL,
  `pesable` tinyint(1) DEFAULT NULL,
  `vigente` tinyint(1) DEFAULT NULL,
  `nro_orden` decimal(5,0) DEFAULT NULL,
  `nro_despacho` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `linea_01` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `linea_02` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `linea_03` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `linea_04` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `linea_05` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `linea_06` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rack` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `esta` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `colu` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `depo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `QI` DECIMAL(20,6) DEFAULT NULL,
  `fchange` date DEFAULT NULL,
  `Desc_Fin` DECIMAL(6,2) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_stock_cod` (`cod`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- tarje
CREATE TABLE IF NOT EXISTS `tarje` (
  `fecha` date DEFAULT NULL,
  `nro_tarje` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cupon` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `moneda` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `importe` decimal(12,2) DEFAULT NULL,
  `estado` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `autoriz` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `factu` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fechal` date DEFAULT NULL,
  `lote` varchar(5) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fecha_liq` date DEFAULT NULL,
  `liq` varchar(13) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tarje` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `form_tipo` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `form_nro` VARCHAR(15),
  `pass` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `relote` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_equi` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codfact` decimal(3,0) DEFAULT NULL,
  `ptovta` decimal(5,0) DEFAULT NULL,
  `nro` decimal(8,0) DEFAULT NULL,
  `codigo` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- tarjetas
CREATE TABLE IF NOT EXISTS `tarjetas` (
  `tarje` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `descrip` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `l_autoriz` decimal(8,2) DEFAULT NULL,
  `descu` decimal(5,2) DEFAULT NULL,
  `cuit` varchar(13) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `plazo_acred` decimal(3,0) DEFAULT NULL,
  `comision` decimal(5,2) DEFAULT NULL,
  `tipo` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `red` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activo` tinyint(1) DEFAULT '1',
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- vendedor
CREATE TABLE IF NOT EXISTS `vendedor` (
  `cod_vend` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vendedor` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `comi_rela` decimal(6,2) DEFAULT NULL,
  `comi_abso` decimal(6,2) DEFAULT NULL,
  `comi_gan` decimal(6,2) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `idx_sync` (`_sync_estado`,`_eliminado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- apr
CREATE TABLE IF NOT EXISTS `apr` (
  `codigo`    VARCHAR(10)   NOT NULL,
  `saldo_cc`  DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `update_at` DATETIME      NULL,
  PRIMARY KEY (`codigo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
