-- ============================================================
--  schema.sql — Schema completo del sistema de gestión
--  Usar: CREATE TABLE IF NOT EXISTS (seguro en bases existentes)
--  Generado: 2026-04-30
--  Subir a: github.com/surisistemas/migraciones/schema.sql
-- ============================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

-- ── Control de versiones ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS `_schema_version` (
  `version`      INT          NOT NULL,
  `descripcion`  VARCHAR(200) NOT NULL DEFAULT '',
  `aplicado_en`  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Clientes ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `acl` (
  `codigo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nombre` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fantasia` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `direc` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_postal` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `locali` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fax` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `telefono` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cuit` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pos` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tipo_pos` decimal(2,0) DEFAULT NULL,
  `tipo_doc` decimal(2,0) DEFAULT NULL,
  `obs` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provi` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cli_pro` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_estado` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_zona` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_vend` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `clasif` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cl_lista` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `monecc` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `saldo_cc` decimal(12,2) DEFAULT NULL,
  `bloqueo_cc` tinyint(1) DEFAULT NULL,
  `apli_licre` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `limite_cre` decimal(12,2) DEFAULT NULL,
  `impri_eti` tinyint(1) DEFAULT NULL,
  `impri_pa` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bonif_1` decimal(5,2) DEFAULT NULL,
  `bonif_12` decimal(5,2) DEFAULT NULL,
  `bonif_13` decimal(5,2) DEFAULT NULL,
  `bonif_2` decimal(5,2) DEFAULT NULL,
  `desc_art` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `t_pago` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `f_pago1` decimal(3,0) DEFAULT NULL,
  `f_pago2` decimal(3,0) DEFAULT NULL,
  `f_pago3` decimal(3,0) DEFAULT NULL,
  `f_pago4` decimal(3,0) DEFAULT NULL,
  `f_pago5` decimal(3,0) DEFAULT NULL,
  `f_pago6` decimal(3,0) DEFAULT NULL,
  `cod_trans` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ulti_ope` date DEFAULT NULL,
  `liberado` decimal(6,2) DEFAULT NULL,
  `iva_exen` tinyint(1) DEFAULT NULL,
  `ib_tipo` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ib_nro` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `iva_porc` decimal(5,2) DEFAULT NULL,
  `ib_exen` tinyint(1) DEFAULT NULL,
  `ib_porc` decimal(5,2) DEFAULT NULL,
  `ib_exen_901` tinyint(1) DEFAULT NULL,
  `ib_porc_901` decimal(5,2) DEFAULT NULL,
  `ib_exen_924` tinyint(1) DEFAULT NULL,
  `ib_porc_924` decimal(5,2) DEFAULT NULL,
  `ib_exen_914` tinyint(1) DEFAULT NULL,
  `ib_porc_914` decimal(5,2) DEFAULT NULL,
  `ib_exen_93` tinyint(1) DEFAULT NULL,
  `ib_porc_93` decimal(5,2) DEFAULT NULL,
  `cl_obs` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cl_anotador` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `impri_opcion` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p_venta` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `f_alta` date DEFAULT NULL,
  `tcompras` decimal(15,2) DEFAULT NULL,
  `modali` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `situa` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mkfecha` date DEFAULT NULL,
  `mkfechaul` date DEFAULT NULL,
  `lote` decimal(5,0) DEFAULT NULL,
  `bonif_22` decimal(5,2) DEFAULT NULL,
  `bonif_23` decimal(5,2) DEFAULT NULL,
  `bonif_3` decimal(5,2) DEFAULT NULL,
  `fcredito` tinyint(1) DEFAULT NULL,
  `fchange` date DEFAULT NULL,
  `id_acl` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_vend2` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ib_porc_94` decimal(6,2) DEFAULT NULL,
  `ib_exen_94` tinyint(1) DEFAULT NULL,
  `c_min` decimal(15,2) DEFAULT NULL,
  `w_user` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ib_exen_921` tinyint(1) NOT NULL DEFAULT '0',
  `ib_porc_921` decimal(5,2) NOT NULL DEFAULT '0.00',
  `ib_exen_917` tinyint(1) NOT NULL DEFAULT '0',
  `ib_porc_917` decimal(5,2) NOT NULL DEFAULT '0.00',
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `acl2` (
  `codigo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `campo` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contenido` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Facturación ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `af` (
  `ffact` date DEFAULT NULL,
  `comprob` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tipo` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codfact` decimal(3,0) DEFAULT NULL,
  `fnfact` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nombre` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ftt` decimal(12,2) DEFAULT NULL,
  `codigo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `direc` varchar(35) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `locali` varchar(35) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cuit` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pos` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tipo_pos` decimal(2,0) DEFAULT NULL,
  `tipo_doc` decimal(2,0) DEFAULT NULL,
  `fst` decimal(12,2) DEFAULT NULL,
  `descu` decimal(10,2) DEFAULT NULL,
  `descu2` decimal(10,2) DEFAULT NULL,
  `reca` decimal(10,2) DEFAULT NULL,
  `n_gra` decimal(12,2) DEFAULT NULL,
  `n_no_gra` decimal(12,2) DEFAULT NULL,
  `impu` decimal(10,2) DEFAULT NULL,
  `iva` decimal(10,2) DEFAULT NULL,
  `iva_105` decimal(10,2) DEFAULT NULL,
  `percep` decimal(10,2) DEFAULT NULL,
  `reib` decimal(10,2) DEFAULT NULL,
  `reib_901` decimal(10,2) DEFAULT NULL,
  `reib_921` decimal(10,2) DEFAULT NULL,
  `reib_917` decimal(10,2) DEFAULT NULL,
  `reib_914` decimal(10,2) DEFAULT NULL,
  `p_descu` decimal(5,2) DEFAULT NULL,
  `p_descu2` decimal(5,2) DEFAULT NULL,
  `p_descu3` decimal(5,2) DEFAULT NULL,
  `p_descu4` decimal(5,2) DEFAULT NULL,
  `p_reca` decimal(5,2) DEFAULT NULL,
  `p_impu` decimal(5,2) DEFAULT NULL,
  `p_percep` decimal(5,2) DEFAULT NULL,
  `p_reib` decimal(5,2) DEFAULT NULL,
  `p_reib_901` decimal(5,2) DEFAULT NULL,
  `p_reib_921` decimal(5,2) DEFAULT NULL,
  `p_reib_917` decimal(5,2) DEFAULT NULL,
  `p_reib_914` decimal(5,2) DEFAULT NULL,
  `cod_zona` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_vend` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `comi_v` decimal(9,2) DEFAULT NULL,
  `moneda` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dolar` decimal(10,4) DEFAULT NULL,
  `remii` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `oc_prov` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `oc_2` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provi` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `libera` decimal(6,2) DEFAULT NULL,
  `cod_fp` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `plazo` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `relote` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `transporte` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `impri_opcion` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `precrd` decimal(1,0) DEFAULT NULL,
  `pass` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cae` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vtocae` date DEFAULT NULL,
  `fe` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reib_924` decimal(12,2) DEFAULT NULL,
  `p_reib_924` decimal(6,2) DEFAULT NULL,
  `fecha` datetime(3) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `_pdf_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_pdf_subido_en` datetime(3) DEFAULT NULL,
  `_pdf_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_pdf_intentos` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `af_obs` (
  `arch` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fnfact` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ffact` date DEFAULT NULL,
  `nro_obs` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `obs` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `afd` (
  `fcant` decimal(6,0) DEFAULT NULL,
  `fcod` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fdesc` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unidad` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fprec` decimal(12,3) DEFAULT NULL,
  `bonif` decimal(4,2) DEFAULT NULL,
  `ftotal` decimal(12,2) DEFAULT NULL,
  `cod_orig` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tipo` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fnfact` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `comprob` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codfact` decimal(3,0) DEFAULT NULL,
  `ftotal_siv` decimal(12,3) DEFAULT NULL,
  `f_pu` decimal(12,3) DEFAULT NULL,
  `f_lista` decimal(12,3) DEFAULT NULL,
  `tribu_iva` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `moneda` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_zona` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_vend` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ffact` date DEFAULT NULL,
  `texva` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `texva2` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codigo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pais` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provi` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tasa_ib` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dolar` decimal(10,4) DEFAULT NULL,
  `relote` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nro_despacho` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `r_codfact` decimal(3,0) DEFAULT NULL,
  `r_ptovta` decimal(5,0) DEFAULT NULL,
  `r_nrocpte` decimal(8,0) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Contabilidad ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `contable` (
  `fecha` date DEFAULT NULL,
  `c_debe` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `c_haber` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `importe` decimal(15,2) DEFAULT NULL,
  `detalle` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `moneda` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dolar` decimal(10,4) DEFAULT NULL,
  `form_tipo` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `form_nro` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `transfe` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `asi` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pass` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sucursal` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Cuenta corriente ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `ctacte_d` (
  `fcc` date DEFAULT NULL,
  `fo` date DEFAULT NULL,
  `codigo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `detalle` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `moneda` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `debe` decimal(12,2) DEFAULT NULL,
  `haber` decimal(12,2) DEFAULT NULL,
  `saldo` decimal(12,2) DEFAULT NULL,
  `dolar` decimal(15,4) DEFAULT NULL,
  `saldo_reg` decimal(12,2) DEFAULT NULL,
  `saldori` decimal(12,2) DEFAULT NULL,
  `comi_reg` decimal(10,2) DEFAULT NULL,
  `cod_vend` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pass` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ptoventa` decimal(5,0) DEFAULT NULL,
  `numero` decimal(8,0) DEFAULT NULL,
  `codfact` decimal(3,0) DEFAULT NULL,
  `fecha` datetime(3) DEFAULT NULL,
  `fchange` datetime(3) DEFAULT NULL,
  `identify` int DEFAULT NULL,
  `cod_vend2` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `comi_reg2` decimal(12,2) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ctacte_h` (
  `fcc` date DEFAULT NULL,
  `fo` date DEFAULT NULL,
  `codigo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `detalle` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `moneda` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `debe` decimal(15,2) DEFAULT NULL,
  `haber` decimal(15,2) DEFAULT NULL,
  `saldo` decimal(15,2) DEFAULT NULL,
  `dolar` decimal(15,4) DEFAULT NULL,
  `saldo_reg` decimal(15,2) DEFAULT NULL,
  `saldori` decimal(12,2) DEFAULT NULL,
  `pass` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codfact` decimal(3,0) DEFAULT NULL,
  `ptoventa` decimal(5,0) DEFAULT NULL,
  `numero` decimal(8,0) DEFAULT NULL,
  `fecha` datetime(3) DEFAULT NULL,
  `fchange` datetime(3) DEFAULT NULL,
  `identify` int DEFAULT NULL,
  `saldo_ori` decimal(15,2) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Configuración ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `da_configuraciones` (
  `clave` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `valor` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `descripcion` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`_id`),
  UNIQUE KEY `idx_clave_unica` (`clave`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Stock ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `depo_st` (
  `cod` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_depo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cant` decimal(11,0) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mstock` (
  `fecha` date DEFAULT NULL,
  `cod` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `e_s` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `motivo` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mov_cant` decimal(9,0) DEFAULT NULL,
  `detalle` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pass` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_depo` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codigo` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `obs` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `stock` (
  `cod` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mat` varchar(70) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `marca` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `linea` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unidad` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cantxbulto` decimal(6,0) DEFAULT NULL,
  `com_minima` decimal(6,0) DEFAULT NULL,
  `moneda` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `plp0` decimal(12,2) DEFAULT NULL,
  `plp` decimal(12,2) DEFAULT NULL,
  `pu` decimal(12,2) DEFAULT NULL,
  `lista1` decimal(12,2) DEFAULT NULL,
  `lista2` decimal(12,2) DEFAULT NULL,
  `lista3` decimal(12,2) DEFAULT NULL,
  `lista4` decimal(12,2) DEFAULT NULL,
  `lista5` decimal(12,2) DEFAULT NULL,
  `lista6` decimal(12,2) DEFAULT NULL,
  `lista7` decimal(12,2) DEFAULT NULL,
  `lista8` decimal(12,2) DEFAULT NULL,
  `s_prec` date DEFAULT NULL,
  `sm` decimal(6,0) DEFAULT NULL,
  `rubro` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `subrubro` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_orig` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pais` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `visible` tinyint(1) DEFAULT NULL,
  `bloqueado` tinyint(1) DEFAULT NULL,
  `imprime` tinyint(1) DEFAULT NULL,
  `cod_orig2` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_orig3` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `impu_c` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `impu_v` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `veriexis` tinyint(1) DEFAULT NULL,
  `comision` decimal(5,2) DEFAULT NULL,
  `falta` date DEFAULT NULL,
  `pass` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pesoxuni` decimal(8,3) DEFAULT NULL,
  `tribu_iva` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tasa_ib` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `st_obs` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `imp_eti` tinyint(1) DEFAULT NULL,
  `f_venta` date DEFAULT NULL,
  `f_compra` date DEFAULT NULL,
  `f_prec` date DEFAULT NULL,
  `f_precbase` date DEFAULT NULL,
  `st_prov` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `st_prov2` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `st_prov3` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bonif` decimal(5,2) DEFAULT NULL,
  `desc_a` decimal(5,2) DEFAULT NULL,
  `desc_b` decimal(5,2) DEFAULT NULL,
  `desc_c` decimal(5,2) DEFAULT NULL,
  `por_prov` decimal(6,2) DEFAULT NULL,
  `por_prov2` decimal(6,2) DEFAULT NULL,
  `por_prov3` decimal(6,2) DEFAULT NULL,
  `por_prov4` decimal(6,2) DEFAULT NULL,
  `por_lista1` decimal(8,3) DEFAULT NULL,
  `por_lista2` decimal(8,3) DEFAULT NULL,
  `por_lista3` decimal(8,3) DEFAULT NULL,
  `por_lista4` decimal(8,3) DEFAULT NULL,
  `por_lista5` decimal(8,3) DEFAULT NULL,
  `por_lista6` decimal(8,3) DEFAULT NULL,
  `por_lista7` decimal(8,3) DEFAULT NULL,
  `por_lista8` decimal(8,3) DEFAULT NULL,
  `ok_grafico` tinyint(1) DEFAULT NULL,
  `grafico` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tecnico` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `barra` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dun14` varchar(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `st_memo` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `mini_lista` tinyint(1) DEFAULT NULL,
  `cavenmi` decimal(6,0) DEFAULT NULL,
  `cavenmip` decimal(3,2) DEFAULT NULL,
  `oferta` decimal(1,0) DEFAULT NULL,
  `scri` decimal(6,0) DEFAULT NULL,
  `std_montaj` decimal(8,3) DEFAULT NULL,
  `web` tinyint(1) DEFAULT NULL,
  `pesable` tinyint(1) DEFAULT NULL,
  `vigente` tinyint(1) DEFAULT NULL,
  `nro_orden` decimal(5,0) DEFAULT NULL,
  `nro_despacho` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `linea_01` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `linea_02` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `linea_03` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `linea_04` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `linea_05` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `linea_06` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rack` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `esta` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `colu` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `depo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `qi` decimal(20,6) DEFAULT NULL,
  `fchange` date DEFAULT NULL,
  `desc_fin` decimal(8,2) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Caja ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `mov_caja` (
  `nro_caja` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fecha_caja` datetime(3) DEFAULT NULL,
  `fecha` date DEFAULT NULL,
  `detalle` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `moneda` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ing_egr` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `importe` decimal(12,2) DEFAULT NULL,
  `saldo` decimal(12,2) DEFAULT NULL,
  `form_tipo` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `form_nro` varchar(13) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dolar` decimal(10,4) DEFAULT NULL,
  `pass` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `relote` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Numeración ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `ncompro` (
  `nro` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `f_a` tinyint(1) DEFAULT NULL,
  `nc_a` tinyint(1) DEFAULT NULL,
  `nd_a` tinyint(1) DEFAULT NULL,
  `f_e` tinyint(1) DEFAULT NULL,
  `f_b` tinyint(1) DEFAULT NULL,
  `nc_b` tinyint(1) DEFAULT NULL,
  `nd_b` tinyint(1) DEFAULT NULL,
  `t_b` tinyint(1) DEFAULT NULL,
  `r_x` tinyint(1) DEFAULT NULL,
  `f_c` tinyint(1) DEFAULT NULL,
  `r_f` tinyint(1) DEFAULT NULL,
  `r_fb` tinyint(1) DEFAULT NULL,
  `pr` tinyint(1) DEFAULT NULL,
  `oc` tinyint(1) DEFAULT NULL,
  `op` tinyint(1) DEFAULT NULL,
  `np` tinyint(1) DEFAULT NULL,
  `reci` tinyint(1) DEFAULT NULL,
  `pc` tinyint(1) DEFAULT NULL,
  `prof` tinyint(1) DEFAULT NULL,
  `confirma` tinyint(1) DEFAULT NULL,
  `retib` tinyint(1) DEFAULT NULL,
  `sucursal` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cotizpro` tinyint(1) DEFAULT NULL,
  `ing_f` tinyint(1) DEFAULT NULL,
  `egr_f` tinyint(1) DEFAULT NULL,
  `cantlinea` decimal(3,0) DEFAULT NULL,
  `reporte` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reporte2` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `impresora` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `elij_imp` tinyint(1) DEFAULT NULL,
  `copias` decimal(2,0) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Pedidos ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `ped` (
  `item` decimal(4,0) DEFAULT NULL,
  `ffact` date DEFAULT NULL,
  `hora` datetime(3) DEFAULT NULL,
  `fvence` date DEFAULT NULL,
  `fnfact` decimal(6,0) DEFAULT NULL,
  `nombre` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ftt` decimal(12,2) DEFAULT NULL,
  `pendiente` tinyint(1) DEFAULT NULL,
  `aprobado` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fec_apro` datetime(3) DEFAULT NULL,
  `preparado` tinyint(1) DEFAULT NULL,
  `f_preparado` datetime(3) DEFAULT NULL,
  `cod_estado` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_preparador` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p_despacho` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codigo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cuit` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pos` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fst` decimal(12,2) DEFAULT NULL,
  `descu` decimal(10,2) DEFAULT NULL,
  `descu2` decimal(10,2) DEFAULT NULL,
  `reca` decimal(10,2) DEFAULT NULL,
  `n_gra` decimal(12,2) DEFAULT NULL,
  `n_no_gra` decimal(12,2) DEFAULT NULL,
  `impu` decimal(10,2) DEFAULT NULL,
  `iva` decimal(10,2) DEFAULT NULL,
  `iva_105` decimal(10,2) DEFAULT NULL,
  `p_descu` decimal(5,2) DEFAULT NULL,
  `p_descu2` decimal(5,2) DEFAULT NULL,
  `p_descu3` decimal(5,2) DEFAULT NULL,
  `p_descu4` decimal(5,2) DEFAULT NULL,
  `p_reca` decimal(5,2) DEFAULT NULL,
  `p_impu` decimal(5,2) DEFAULT NULL,
  `cod_vend` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `moneda` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dolar` decimal(10,4) DEFAULT NULL,
  `provi` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `libera` decimal(6,2) DEFAULT NULL,
  `cod_fp` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `plazo` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fentre` date DEFAULT NULL,
  `hentre` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pesot` decimal(8,3) DEFAULT NULL,
  `lote` decimal(5,0) DEFAULT NULL,
  `np_oc` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `np_oc_2` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lista` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `precrd` decimal(1,0) DEFAULT NULL,
  `pass_apro` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pass` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p_reib` decimal(5,2) DEFAULT NULL,
  `p_reib_901` decimal(5,2) DEFAULT NULL,
  `p_reib_921` decimal(5,2) DEFAULT NULL,
  `p_reib_917` decimal(5,2) DEFAULT NULL,
  `p_reib_914` decimal(5,2) DEFAULT NULL,
  `reib` decimal(10,2) DEFAULT NULL,
  `reib_901` decimal(10,2) DEFAULT NULL,
  `reib_921` decimal(10,2) DEFAULT NULL,
  `reib_914` decimal(10,2) DEFAULT NULL,
  `reib_917` decimal(10,2) DEFAULT NULL,
  `fchange` datetime(3) DEFAULT NULL,
  `tipo_pos` decimal(2,0) DEFAULT NULL,
  `tipo_doc` decimal(2,0) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ped_d` (
  `fcant` decimal(6,0) DEFAULT NULL,
  `menos` decimal(6,0) DEFAULT NULL,
  `pendi` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dentrega` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `item` decimal(4,0) DEFAULT NULL,
  `cnt_preparada` decimal(6,0) DEFAULT NULL,
  `preparado` tinyint(1) DEFAULT NULL,
  `f_preparado` datetime(3) DEFAULT NULL,
  `cod_preparada` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_preparo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cod_estado` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fcod` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fdesc` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unidad` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `f_pu` decimal(15,2) DEFAULT NULL,
  `fprec` decimal(12,2) DEFAULT NULL,
  `bonif` decimal(4,2) DEFAULT NULL,
  `ftotal` decimal(12,2) DEFAULT NULL,
  `cod_orig` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tribu_iva` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codigo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ffact` date DEFAULT NULL,
  `cod_vend` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `texva` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `texva2` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fnfact` decimal(6,0) DEFAULT NULL,
  `lote` decimal(5,0) DEFAULT NULL,
  `nro_despacho` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fchange` datetime(3) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Presupuestos ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `pre` (
  `ffact` date DEFAULT NULL,
  `hora` datetime(3) DEFAULT NULL,
  `fvence` date DEFAULT NULL,
  `aprobado` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `autorizado` tinyint(1) DEFAULT NULL,
  `user_autori` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fnfact` decimal(6,0) DEFAULT NULL,
  `nombre` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ftt` decimal(12,2) DEFAULT NULL,
  `codigo` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cuit` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pos` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fst` decimal(12,2) DEFAULT NULL,
  `descu` decimal(10,2) DEFAULT NULL,
  `descu2` decimal(10,2) DEFAULT NULL,
  `reca` decimal(10,2) DEFAULT NULL,
  `n_gra` decimal(12,2) DEFAULT NULL,
  `n_no_gra` decimal(12,2) DEFAULT NULL,
  `impu` decimal(10,2) DEFAULT NULL,
  `iva` decimal(10,2) DEFAULT NULL,
  `iva_105` decimal(10,2) DEFAULT NULL,
  `p_descu` decimal(5,2) DEFAULT NULL,
  `p_descu2` decimal(5,2) DEFAULT NULL,
  `p_descu3` decimal(5,2) DEFAULT NULL,
  `p_descu4` decimal(5,2) DEFAULT NULL,
  `p_reca` decimal(5,2) DEFAULT NULL,
  `p_impu` decimal(5,2) DEFAULT NULL,
  `cod_vend` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `moneda` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dolar` decimal(10,4) DEFAULT NULL,
  `provi` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `libera` decimal(6,2) DEFAULT NULL,
  `cod_fp` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `plazo` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lote` decimal(5,0) DEFAULT NULL,
  `lista` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `precrd` decimal(1,0) DEFAULT NULL,
  `pass` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `p_reib` decimal(5,2) DEFAULT NULL,
  `p_reib_921` decimal(5,2) DEFAULT NULL,
  `p_reib_901` decimal(5,2) DEFAULT NULL,
  `p_reib_914` decimal(10,2) DEFAULT NULL,
  `p_reib_917` decimal(5,2) DEFAULT NULL,
  `reib` decimal(10,2) DEFAULT NULL,
  `reib_901` decimal(10,2) DEFAULT NULL,
  `reib_921` decimal(10,2) DEFAULT NULL,
  `reib_917` decimal(10,2) DEFAULT NULL,
  `reib_914` decimal(10,2) DEFAULT NULL,
  `fchange` datetime(3) DEFAULT NULL,
  `tipo_pos` decimal(2,0) DEFAULT NULL,
  `tipo_doc` decimal(2,0) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `pre_d` (
  `fcant` decimal(6,0) DEFAULT NULL,
  `dentrega` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `item` decimal(4,0) DEFAULT NULL,
  `fcod` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fdesc` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unidad` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `f_pu` decimal(15,2) DEFAULT NULL,
  `fprec` decimal(12,3) DEFAULT NULL,
  `bonif` decimal(4,2) DEFAULT NULL,
  `ftotal` decimal(12,2) DEFAULT NULL,
  `cod_orig` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fnfact` decimal(6,0) DEFAULT NULL,
  `tribu_iva` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ffact` date DEFAULT NULL,
  `texva` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `texva2` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lote` decimal(5,0) DEFAULT NULL,
  `nro_despacho` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fchange` datetime(3) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Vendedores / Monedas ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS `vendedor` (
  `cod_vend` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vendedor` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `comi_rela` decimal(6,2) DEFAULT NULL,
  `comi_abso` decimal(6,2) DEFAULT NULL,
  `comi_gan` decimal(6,2) DEFAULT NULL,
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT (uuid()),
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `syncro_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `monedas` (
  `moneda` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `descripcion` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cotizacion` decimal(12,2) NOT NULL DEFAULT '1.00',
  `_id` bigint NOT NULL AUTO_INCREMENT,
  `_uuid` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `_creado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `_modificado_en` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `_sincronizado_en` datetime(3) DEFAULT NULL,
  `_sync_estado` tinyint(1) NOT NULL DEFAULT '0',
  `_sync_version` int NOT NULL DEFAULT '1',
  `_origen` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MIGRADOR',
  `_eliminado` tinyint(1) NOT NULL DEFAULT '0',
  `_eliminado_en` datetime(3) DEFAULT NULL,
  `_hash` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `_api_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`_id`),
  UNIQUE KEY `idx_moneda_unica` (`moneda`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Auditoría / Extras ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS `auditoria` (
  `id` int NOT NULL AUTO_INCREMENT,
  `fecha` datetime DEFAULT NULL,
  `comando` char(10) DEFAULT NULL,
  `data` text,
  `tabla` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `exchange_rates` (
  `currency` char(3) NOT NULL,
  `rate_ars` decimal(18,6) NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`currency`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS=1;

-- ============================================================
--  FIN DEL SCHEMA
-- ============================================================